site_name: COMP423 Course Notes
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg